## EXPERIMENT NUMBER ##
experiment: 1
## INPUT SIZE ##
batch_size: 8
width: 96
height: 96
## DATA HYPERPARAMS ##
max_limit: 500000000
percentage_train: 0.8
concat_zero: False
## TRAINING HYPERPARAMS ##
epochs: 50
lr: 1e-4
weight_decay: 0
## MODEL HYPERPARAMS ##
n_aug_blocks: 0
upsampling_method: "bilinear"
conv_TF: "tanh"
block_TF: "tanh"
out_TF: "sigmoid"
## CONTENT LOSS HYPERPARAMS ##
feature_name: "features.35"
feature_mean: [0.485, 0.456, 0.406]
feature_std: [0.229, 0.224, 0.225]
content_weight: 1
adversarial_weight: 0.001
